Module3 task1
htmlacademy-javascript/978921-keksobooking-21 pull request #2
Opened 2020-10-04 11:59 UTC by artkerr

2020-10-04 13:07 UTC, Shv-sergey70 requested changes

2020-10-04 13:07 UTC, Shv-sergey70 commented on js/main.js
> +  pinButton.setAttribute(`style`, `left: ${data.location.x - pinButton.offsetWidth}px; top: ${data.location.y - pinButton.offsetHeight}px;`);
Попробуй так менять стили и атрибуты:
```
pinButton.style.top = `${data.location.y - pinButton.offsetHeight}px`;
  pinButton.style.left = `${data.location.x - pinButton.offsetWidth}px`;
```
Это более гибко.
Ниже `src, alt` можно переписать также

2020-10-04 13:07 UTC, Shv-sergey70 commented on js/main.js
> +const createPin = (data) => {
`data` очень общее название для аргумента. Нужно стараться давать максимально релевантное название переменной

2020-10-04 13:07 UTC, Shv-sergey70 commented on js/main.js
> +      y: getRandomNumber(130, 630)
1. Эти цифры нужно вынести в константы.
2. Данные `x, y` должны совпадать с теми, что записываются в поле `address` текущего объекта

2020-10-04 13:07 UTC, Shv-sergey70 commented on js/main.js
> +      guests: `${getRandomNumber(1, 10)}`,
Все цифры должны быть в константах/перечислениях

2020-10-06 07:33 UTC, Shv-sergey70 requested changes

2020-10-06 07:33 UTC, Shv-sergey70 commented on js/main.js
> +const OFFER_TITLE = [`Апартаменты-студия`, `Аппартаменты в центре`, `Дом за городом`, `Малокомнатная квартира`, `Многокомнатная квартира`, `Несколькокомнатная квартира`];
Если в переменной хранится массив, то название переменной должно быть во множественном числе: `OFFER_TITLES`

2020-10-06 07:33 UTC, Shv-sergey70 commented on js/main.js
> +const PRICE = {
Посмотри как правильно оформлять перечисление:
https://up.htmlacademy.ru/javascript/21/criteries#b8

Это должно выглядеть так:
```
const Price = {
  MIN: 10000,
  MAX: 100000
};
```

2020-10-06 07:33 UTC, Shv-sergey70 commented on js/main.js
> +  const MAP_Y = getRandomNumber(MARK_Y.min, MARK_Y.max);
В верхнем регистре мы именуем только реальные константы - то что не может измениться и не генерируется динамически. В данном случае, это обычные переменные

2020-10-06 07:33 UTC, Shv-sergey70 commented on js/main.js
> +  return newAdvert;
Можно обойтись без переменной `newAdvert` и сделать сразу так:
```
const getAdvert = () => {
  const MAP_X = getRandomNumber(0, activeMap.offsetWidth);
  const MAP_Y = getRandomNumber(MARK_Y.min, MARK_Y.max);

  return {
    autor: {
      avatar: `img/avatars/user0${getRandomNumber(1, ADVERT_QUANTITY)}.png`
    },
    offer: {
      title: getRandomElement(OFFER_TITLE),
      address: `${MAP_X}, ${MAP_Y}`,
      price: getRoundNum(getRandomNumber(PRICE.min, PRICE.max)),
      type: getRandomElement(OFFER_TYPE),
      rooms: `${getRandomNumber(ROOMS.min, ROOMS.max)}`,
      guests: `${getRandomNumber(GUESTS.min, GUESTS.max)}`,
      checkin: getRandomElement(OFFER_CHECKIN_CHECKOUT),
      checkout: getRandomElement(OFFER_CHECKIN_CHECKOUT),
      features: OFFER_FEATURES.slice(0, getRandomNumber(0, OFFER_FEATURES.length)),
      description: getRandomElement(OFFER_DESCRIPTION),
      photos: getRandomElement(OFFER_PHOTOS)
    },
    location: {
      x: MAP_X,
      y: MAP_Y
    }
  };
};
```

2020-10-06 07:33 UTC, Shv-sergey70 commented on js/main.js
> +    autor: {
Опечатка `autor` -> `author`

2020-10-06 07:33 UTC, Shv-sergey70 commented on js/main.js
> +const getRoundNum = (num) => Math.round(num / 1000) * 1000;
Не нужно делать сокращения в названиях переменных/функциях - это почти всегда ухудшает читаемость кода. Это я о `Num`

2020-10-06 07:33 UTC, Shv-sergey70 commented on js/main.js
> +const getRandomElement = (arr) => arr[Math.floor(Math.random() * arr.length)];
`arr` - это все же отражение структуры данных в названии, поэтому лучше так:
`arr` -> `items`.

2020-10-06 07:33 UTC, Shv-sergey70 commented on js/main.js
> +const generateAdvertArr = (quantity) => {
Можно назвать просто `generateAdverts`

2020-10-06 07:33 UTC, Shv-sergey70 commented on js/main.js
> +};
Зачем создавать массив снаружи функции, и уже внутри функции заполнять его и возвращать? Ты же можешь создать массив прямо внутри функции:
```
const generateAdvertArr = (quantity) => {
  const adverts = [];

  for (let i = 0; i < quantity; i++) {
    adverts.push(getAdvert());
  }

  return adverts;
};
```

Тогда на 94 строке:
`const advertList = generateAdvertArr(ADVERT_QUANTITY);`

2020-10-06 07:33 UTC, Shv-sergey70 commented on js/main.js
> +  pinPhoto.alt = `${pinData.offer.title}`;
А зачем нужно оборачивать в шаблонные строки значения, которые ты присваиваешь на 87-88 строках? Там же не вставляется какой-то текст как на 86 строке (добавляется px).
Можно сразу:
```
  pinPhoto.src = pinData.offer.photos;
  pinPhoto.alt = pinData.offer.title;
```

2020-10-06 07:33 UTC, Shv-sergey70 commented on js/main.js
> +      guests: `${getRandomNumber(GUESTS.min, GUESTS.max)}`,
Зачем здесь использовать шаблонные строки?

2020-10-08 08:32 UTC, artkerr commented on js/main.js
> +};
Может вовсе обойтись без advertList?

generateAdvertArr(ADVERT_QUANTITY);.forEach((pin) => {
  fragment.appendChild(createPin(pin));
});
pinsList.appendChild(fragment);

2020-10-08 09:06 UTC, Shv-sergey70 commented on js/main.js
> +};
Можно еще так:
```
const getAdvert = () => {
  const location = {
    x: getRandomNumber(0, activeMap.offsetWidth),
    y: getRandomNumber(MarkY.MIN, MarkY.MAX)
  };

  return {
    author: {
      avatar: `img/avatars/user0${getRandomNumber(1, ADVERT_QUANTITY)}.png`
    },
    offer: {
      title: getRandomElement(OFFER_TITLES),
      address: `${location.x}, ${location.y}`,
      price: getRoundNumber(getRandomNumber(Price.MIN, Price.MAX)),
      type: getRandomElement(OFFER_TYPES),
      rooms: getRandomNumber(Rooms.MIN, Rooms.MAX),
      guests: getRandomNumber(Guests.MIN, Guests.MAX),
      checkin: getRandomElement(OFFER_CHECKIN_CHECKOUT_TIMES),
      checkout: getRandomElement(OFFER_CHECKIN_CHECKOUT_TIMES),
      features: OFFER_FEATURES.slice(0, getRandomNumber(0, OFFER_FEATURES.length)),
      description: getRandomElement(OFFER_DESCRIPTIONS),
      photos: getRandomElement(OFFER_PHOTOS)
    },
    location
  };
};
```

2020-10-08 09:06 UTC, merged